---
name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: none
  id-token: none
  security-events: none
  packages: none

jobs:
  call_reusable_vuln_scan:
    name: OSV-Scanner
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
      packages: write
    uses: complytime/org-infra/.github/workflows/reusable_vuln_scan.yml@cfd981e757253218aefb37c91969c32827e5c4b1 # v0.2.1

  call_reusable_security:
    name: OpenSSF Scorecards
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: complytime/org-infra/.github/workflows/reusable_security.yml@cfd981e757253218aefb37c91969c32827e5c4b1 # v0.2.1
