---
name: Scheduled Jobs

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  actions: none
  id-token: none
  security-events: none

jobs:
  call_reusable_scheduled:
    name: OSV-Scanner and Scorecards
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
    uses: complytime/org-infra/.github/workflows/reusable_scheduled.yml@32b8e9b381a33fc4c3f8768856b11d94655f20c4 # main
