---
name: Scheduled Jobs

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  actions: none
  id-token: none
  security-events: none

jobs:
  call_reusable_scheduled:
    name: OSV-Scanner and Scorecards
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
    uses: complytime/org-infra/.github/workflows/reusable_scheduled.yml@cfd981e757253218aefb37c91969c32827e5c4b1 # v0.2.1
